// project: SeamlyLayout
// author: slspencer, copyright 2026
// MIT License: https://opensource.org/licenses/MIT

//! @brief Drawing and block structures for ezdxf-like intermediate representation.

use crate::astm_contour::AstmContour;
use crate::astm_notch::Notch;
use crate::entities::{Entity, Point};

// @brief DXF version enumeration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum DxfVersion {
    // DXF R12 (AC1009): the widest importer support.
    #[default]
    R12,
    // DXF R13 (AC1012): the version ASTM D6673 §1.2 names.
    R13,
}

// @brief Annotation text of a piece (DXF layer 15), in DXF units.
#[derive(Debug, Clone, PartialEq)]
pub struct Annotation {
    // Insertion point.
    pub position: Point,
    // Text height.
    pub height: f64,
    // Rotation in degrees counter-clockwise.
    pub rotation: f64,
    // Text content (ASCII-only).
    pub text: String,
}

// @brief Block definition: one pattern piece.
//
// `entities` holds the generic conversion of every SVG element. The ASTM fields
// hold the same piece classified by `data-type`, in DXF units; the DXF-ASTM
// writer uses them whenever `boundary` is present.
pub struct Block {
    // Block name (ASCII-only, sanitized, with "_M" suffix).
    pub name: String,
    // All converted entities (generic, used for validation and inspection).
    pub entities: Vec<Box<dyn Entity>>,
    // `Piece Name:` system text (piece `data-name`, else the block name).
    pub piece_name: String,
    // `Quantity:` system text in "R,L" form, when the piece label states it.
    pub quantity: Option<String>,
    // Piece boundary (layer 1 / 84).
    pub boundary: Option<AstmContour>,
    // Sew lines (layer 14 / 87).
    pub sew_lines: Vec<AstmContour>,
    // Internal lines (layer 8 / 85).
    pub internal_lines: Vec<AstmContour>,
    // Internal cutouts (layer 11 / 86).
    pub cutouts: Vec<AstmContour>,
    // Grainline start and end points (layer 7), if present.
    pub grainline: Option<(Point, Point)>,
    // Notches (layers 4, 80, 81, 83).
    pub notches: Vec<Notch>,
    // Annotation text (layer 15).
    pub annotations: Vec<Annotation>,
}

impl Block {
    // @brief Create a new empty block.
    // @param name Block name (should already include "_M" suffix).
    // @return New block whose piece name is the block name.
    pub fn new(name: String) -> Self {
        Self {
            piece_name: name.clone(),
            name,
            entities: Vec::new(),
            quantity: None,
            boundary: None,
            sew_lines: Vec::new(),
            internal_lines: Vec::new(),
            cutouts: Vec::new(),
            grainline: None,
            notches: Vec::new(),
            annotations: Vec::new(),
        }
    } // fn new

    // @brief Add an entity to this block.
    // @param entity Entity to add.
    pub fn add_entity(&mut self, entity: Box<dyn Entity>) {
        self.entities.push(entity);
    } // fn add_entity
} // impl Block

// @brief Drawing (ezdxf-like intermediate representation).
pub struct Drawing {
    // DXF version.
    pub version: DxfVersion,
    // Block definitions (pattern pieces).
    pub blocks: Vec<Block>,
    // Entities in modelspace (not in blocks).
    pub modelspace_entities: Vec<Box<dyn Entity>>,
    // Pattern name from the `data-type="pattern"` group, if the SVG has one.
    pub style_name: Option<String>,
}

impl Drawing {
    // @brief Create a new drawing.
    // @param version DXF version.
    // @return New drawing.
    pub fn new(version: DxfVersion) -> Self {
        Self {
            version,
            blocks: Vec::new(),
            modelspace_entities: Vec::new(),
            style_name: None,
        }
    }

    // @brief Add a block to the drawing.
    // @param block Block to add.
    pub fn add_block(&mut self, block: Block) {
        self.blocks.push(block);
    }

    // @brief Add an entity to modelspace.
    // @param entity Entity to add.
    pub fn add_modelspace_entity(&mut self, entity: Box<dyn Entity>) {
        self.modelspace_entities.push(entity);
    }

    // @brief Write drawing to a human-readable text file for inspection.
    // @param file_path Path to write the file.
    // @return Result indicating success or error.
    pub fn write_to_file(&self, file_path: impl AsRef<std::path::Path>) -> std::io::Result<()> {
        use std::io::Write;

        let mut file = std::fs::File::create(file_path)?;

        writeln!(file, "// SeamlyLayout ezdxf Drawing Inspection File")?;
        writeln!(file, "// Generated by seamly_svg2ezdxf")?;
        writeln!(file, "")?;

        writeln!(file, "DXF Version: {:?}", self.version)?;
        writeln!(file, "Blocks: {}", self.blocks.len())?;
        writeln!(
            file,
            "Modelspace Entities: {}",
            self.modelspace_entities.len()
        )?;
        writeln!(file, "")?;

        if !self.blocks.is_empty() {
            writeln!(file, "=== BLOCKS ===")?;
            for (i, block) in self.blocks.iter().enumerate() {
                writeln!(file, "Block {}: '{}'", i, block.name)?;
                writeln!(file, "  Entity count: {}", block.entities.len())?;
                for (j, entity) in block.entities.iter().enumerate() {
                    writeln!(
                        file,
                        "  Entity {}: {} on layer '{}'",
                        j,
                        entity.entity_type(),
                        entity.layer()
                    )?;
                }
                writeln!(file, "")?;
            }
        }

        if !self.modelspace_entities.is_empty() {
            writeln!(file, "=== MODELSPACE ENTITIES ===")?;
            for (i, entity) in self.modelspace_entities.iter().enumerate() {
                writeln!(
                    file,
                    "Entity {}: {} on layer '{}'",
                    i,
                    entity.entity_type(),
                    entity.layer()
                )?;
            }
        }

        Ok(())
    }
}
