// project: SeamlyLayout
// author: slspencer, copyright 2026
// MIT License: https://opensource.org/licenses/MIT

//! @brief Drawing and block structures for ezdxf-like intermediate representation.

use crate::entities::{Entity, Point};

// @brief DXF version enumeration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DxfVersion {
    // DXF R12 (AC1009) - Required for ASTM-D6673-10.
    R12,
    // DXF R13 (AC1012) - Alternative if needed.
    R13,
}

// @brief Block definition containing entities and CLO3D semantic fields.
//
// The `entities` vec holds all converted SVG geometry for general-purpose use.
// The semantic fields (`boundary_vertices`, `corner_flags`, `grainline`, `notches`)
// are populated by a post-processing pass in the converter and are used by
// `write_blocks_section` to produce CLO3D-compatible DXF output matching
// the structure from seamly2clo.py.
pub struct Block {
    // Block name (ASCII-only, sanitized, with "_M" suffix).
    pub name: String,
    // All converted entities (generic, used for validation and inspection).
    pub entities: Vec<Box<dyn Entity>>,
    // Boundary / cutline polyline vertices (layer 1).
    // Populated from the first Polyline on layer "1" in `entities`.
    pub boundary_vertices: Vec<Point>,
    // Per-vertex corner classification matching `boundary_vertices`.
    // `true` → turn point (layer 2), `false` → curve point (layer 3).
    // Computed by `detect_corners` with a 120° angle threshold.
    pub corner_flags: Vec<bool>,
    // Grainline start and end points (layer 7), if present.
    pub grainline: Option<(Point, Point)>,
    // Notch line segment endpoints (layer 4), one tuple per notch.
    pub notches: Vec<(Point, Point)>,
}

impl Block {
    // @brief Create a new empty block.
    // @param name Block name (should already include "_M" suffix).
    // @return New block.
    pub fn new(name: String) -> Self {
        Self {
            name,
            entities: Vec::new(),
            boundary_vertices: Vec::new(),
            corner_flags: Vec::new(),
            grainline: None,
            notches: Vec::new(),
        }
    } // fn new

    // @brief Add an entity to this block.
    // @param entity Entity to add.
    pub fn add_entity(&mut self, entity: Box<dyn Entity>) {
        self.entities.push(entity);
    } // fn add_entity
} // impl Block

// @brief Drawing (ezdxf-like intermediate representation).
pub struct Drawing {
    // DXF version.
    pub version: DxfVersion,
    // Block definitions (pattern pieces).
    pub blocks: Vec<Block>,
    // Entities in modelspace (not in blocks).
    pub modelspace_entities: Vec<Box<dyn Entity>>,
}

impl Drawing {
    // @brief Create a new drawing.
    // @param version DXF version.
    // @return New drawing.
    pub fn new(version: DxfVersion) -> Self {
        Self {
            version,
            blocks: Vec::new(),
            modelspace_entities: Vec::new(),
        }
    }

    // @brief Add a block to the drawing.
    // @param block Block to add.
    pub fn add_block(&mut self, block: Block) {
        self.blocks.push(block);
    }

    // @brief Add an entity to modelspace.
    // @param entity Entity to add.
    pub fn add_modelspace_entity(&mut self, entity: Box<dyn Entity>) {
        self.modelspace_entities.push(entity);
    }

    // @brief Write drawing to a human-readable text file for inspection.
    // @param file_path Path to write the file.
    // @return Result indicating success or error.
    pub fn write_to_file(&self, file_path: impl AsRef<std::path::Path>) -> std::io::Result<()> {
        use std::io::Write;

        let mut file = std::fs::File::create(file_path)?;

        writeln!(file, "// SeamlyLayout ezdxf Drawing Inspection File")?;
        writeln!(file, "// Generated by seamly_svg2ezdxf")?;
        writeln!(file, "")?;

        writeln!(file, "DXF Version: {:?}", self.version)?;
        writeln!(file, "Blocks: {}", self.blocks.len())?;
        writeln!(
            file,
            "Modelspace Entities: {}",
            self.modelspace_entities.len()
        )?;
        writeln!(file, "")?;

        if !self.blocks.is_empty() {
            writeln!(file, "=== BLOCKS ===")?;
            for (i, block) in self.blocks.iter().enumerate() {
                writeln!(file, "Block {}: '{}'", i, block.name)?;
                writeln!(file, "  Entity count: {}", block.entities.len())?;
                for (j, entity) in block.entities.iter().enumerate() {
                    writeln!(
                        file,
                        "  Entity {}: {} on layer '{}'",
                        j,
                        entity.entity_type(),
                        entity.layer()
                    )?;
                }
                writeln!(file, "")?;
            }
        }

        if !self.modelspace_entities.is_empty() {
            writeln!(file, "=== MODELSPACE ENTITIES ===")?;
            for (i, entity) in self.modelspace_entities.iter().enumerate() {
                writeln!(
                    file,
                    "Entity {}: {} on layer '{}'",
                    i,
                    entity.entity_type(),
                    entity.layer()
                )?;
            }
        }

        Ok(())
    }
}
