// project: SeamlyLayout
// author: slspencer, copyright 2026
// MIT License: https://opensource.org/licenses/MIT

//! @brief Layer mapping from SVG element IDs to ASTM-D6673-10 numeric layer numbers.
//!
//! ASTM-D6673-10 numeric layers (matches CLO3D / seamly2clo.py output):
//! | Layer | Purpose |
//! |-------|---------|
//! | 1     | Piece boundary / cutline |
//! | 2     | Turn points (corners) — generated by corner detection |
//! | 3     | Curve points — generated by corner detection |
//! | 4     | Notches |
//! | 7     | Grainline |
//! | 8     | Internal lines (default) |
//! | 9     | Text / annotations |
//! | 13    | Drill holes |
//! | 14    | Sewing line (mirror of boundary with group 250=2) |

/// @brief Map an SVG element to an ASTM-D6673-10 numeric layer string.
/// @param element The SVG element to map.
/// @return Static ASTM numeric layer string ("1", "4", "7", etc.).
pub fn map_svg_to_astm_layer(element: &xmltree::Element) -> &'static str {
    // Check element ID for layer hints.
    if let Some(id) = element.attributes.get("id") {
        let id_lower = id.to_lowercase();

        if id_lower.contains("cutline") || id_lower.contains("boundary") {
            return "1"; // Layer 1: piece boundary
        } else if id_lower.contains("notch") {
            return "4"; // Layer 4: notches
        } else if id_lower.contains("grainline") || id_lower.contains("grain") {
            return "7"; // Layer 7: grainline
        } else if id_lower.contains("seamline") || id_lower.contains("seam") {
            return "14"; // Layer 14: sewing line
        } else if id_lower.contains("drill") || id_lower.contains("hole") {
            return "13"; // Layer 13: drill holes
        } else if id_lower.contains("tuck") {
            return "8"; // Layer 8: internal lines (tuck/dart construction marks)
        }
    } // if id attribute present

    // Check element tag for text.
    match element.name.as_str() {
        "text" => "9",  // Layer 9: text/annotations
        _ => "8",       // Layer 8: internal lines (default)
    } // match element name
}
