Seamly2D: SvgGenerator Class Reference
SvgGenerator Class Reference
#include <svg_generator.h>
Public Member Functions
SvgGenerator (QGraphicsRectItem *paper, QString name, QString description, int resolution)
void addSvgFromScene (QGraphicsScene *scene)
Add a new SVG to the list of SVGs to be merged into a single SVG.
void generate ()
Generate the merged SVG where each previously given scene is grouped separately.
Private Member Functions
QDomDocument mergeSvgDoms ()
Merge all the SVGs in the m_domList list into a single SVG.
Private Attributes
QGraphicsRectItem * m_paper
QString m_filepath
QString m_description
int m_resolution
QList< QDomDocument > m_domList
Detailed Description
Definition at line 37 of file svg_generator.h.
Constructor & Destructor Documentation
SvgGenerator()
SvgGenerator::SvgGenerator (QGraphicsRectItem * paper, QString name, QString description, int resolution)
Definition at line 40 of file svg_generator.cpp.
Member Function Documentation
addSvgFromScene()
void SvgGenerator::addSvgFromScene (QGraphicsScene * scene)
Add a new SVG to the list of SVGs to be merged into a single SVG.
Parameters
scene : the scene that must be converted to SVG
Returns
void
This function creates a SVG from the given scene and converts it into a DOM that is added to the m_domList list of SVGs to be merged.
Definition at line 102 of file svg_generator.cpp.
References m_description, m_domList, m_paper, and m_resolution.
Referenced by MainWindowsNoGUI::exportSVG(), and MainWindowsNoGUI::exportSVG().
generate()
void SvgGenerator::generate ()
Generate the merged SVG where each previously given scene is grouped separately.
Returns
void
This function merges the SVGs of the m_domList list and writes the result in a file at the path given in the constructor.
Definition at line 144 of file svg_generator.cpp.
References m_filepath, and mergeSvgDoms().
Referenced by MainWindowsNoGUI::exportSVG(), and MainWindowsNoGUI::exportSVG().
mergeSvgDoms()
QDomDocument SvgGenerator::mergeSvgDoms () private
Merge all the SVGs in the m_domList list into a single SVG.
Returns
The merged SVG as a DOM document
m_domList contains DOM representations of multiple SVGs Assuming each svg contains a main group containing every graphical item of the svg, this function adds to the first svg of the list all the main groups of the other svgs, thus creating a single svg with each svg of the list in it, every svg being in its own group. This function is used in order to create svgs containing groups
Definition at line 59 of file svg_generator.cpp.
References m_domList.
Referenced by generate().
Member Data Documentation
m_description
QString SvgGenerator::m_description private
Definition at line 50 of file svg_generator.h.
Referenced by addSvgFromScene().
m_domList
QList<QDomDocument> SvgGenerator::m_domList private
Definition at line 53 of file svg_generator.h.
Referenced by addSvgFromScene(), and mergeSvgDoms().
m_filepath
QString SvgGenerator::m_filepath private
Definition at line 49 of file svg_generator.h.
Referenced by generate().
m_paper
QGraphicsRectItem* SvgGenerator::m_paper private
Definition at line 48 of file svg_generator.h.
Referenced by addSvgFromScene().
m_resolution
int SvgGenerator::m_resolution private
Definition at line 51 of file svg_generator.h.
Referenced by addSvgFromScene().
The documentation for this class was generated from the following files:
src/libs/vformat/svg_generator.h
src/libs/vformat/svg_generator.cpp