# MIT License: https://opensource.org/licenses/MIT
[package]
name = "app_core"
version = "0.1.0"
edition = "2021"
authors = ["slspencer"]
license = "MIT"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
svg_dom = { path = "../svg_dom" }
usvg = "0.42"
resvg = { version = "0.42" }
svg2pdf = "0.11"
xmltree = "0.10"
png = "0.17"
