Seamly2D: qmu::QmuParserToken< TBase, TString > Class Template Reference
qmu::QmuParserToken< TBase, TString > Class Template Reference
Encapsulation of the data for a single formula token.
#include <qmuparsertoken.h>
Public Member Functions
QmuParserToken ()
Constructor (default).
QmuParserToken (const QmuParserToken &a_Tok)
Create token from another one.
QmuParserToken & operator= (const QmuParserToken &a_Tok)
Assignement operator.
void Assign (const QmuParserToken &a_Tok)
Copy token information from argument.
QmuParserToken & Set (ECmdCode a_iType, const TString &a_strTok=TString())
Assign a token type.
QmuParserToken & Set (const QmuParserCallback &a_pCallback, const TString &a_sTok)
Set Callback type.
QmuParserToken & SetVal (TBase a_fVal, const TString &a_strTok=TString())
Make this token a value token.
QmuParserToken & SetVar (TBase *a_pVar, const TString &a_strTok)
make this token a variable token.
QmuParserToken & SetString (const TString &a_strTok, int a_iSize)
Make this token a variable token.
void SetIdx (int a_iIdx)
Set an index associated with the token related data.
int GetIdx () const
Return Index associated with the token related data.
ECmdCode GetCode () const
Return the token type.
ETypeCode GetType () const
int GetPri () const
EOprtAssociativity GetAssociativity () const
generic_fun_type GetFuncAddr () const
Return the address of the callback function assoziated with function and operator tokens.
TBase GetVal () const
Get value of the token.
TBase * GetVar () const
Get address of a variable token.
int GetArgCount () const
Return the number of function arguments.
const TString & GetAsString () const
Return the token identifier.
Static Public Member Functions
template<class FunctionPtr >
static FunctionPtr union_cast (void *objectPtr)
Private Attributes
ECmdCode m_iCode
Type of the token; The token type is a constant of type ECmdCode.
ETypeCode m_iType
void * m_pTok
Stores Token pointer; not applicable for all tokens.
int m_iIdx
An otional index to an external buffer storing the token data.
TString m_strTok
Token string.
TString m_strVal
Value for string variables.
qreal m_fVal
the value
std::unique_ptr< QmuParserCallback > m_pCallback
Detailed Description
template<typename TBase, typename TString>
class qmu::QmuParserToken< TBase, TString >
Encapsulation of the data for a single formula token.
Formula token implementation. Part of the Math Parser Package. Formula tokens can be either one of the following:
value
variable
function with numerical arguments
functions with a string as argument
prefix operators
infix operators
binary operator
Author
(C) 2004-2013 Ingo Berg
Definition at line 58 of file qmuparsertoken.h.
Constructor & Destructor Documentation
QmuParserToken() [1/2]
template<typename TBase , typename TString > qmu::QmuParserToken< TBase, TString >::QmuParserToken () inline
Constructor (default).
Sets token to an neutral state of type cmUNKNOWN.
Exceptions
nothrow
See also
ECmdCode
Definition at line 69 of file qmuparsertoken.h.
QmuParserToken() [2/2]
template<typename TBase , typename TString > qmu::QmuParserToken< TBase, TString >::QmuParserToken (const QmuParserToken< TBase, TString > & a_Tok) inline
Create token from another one.
Implemented by calling Assign(...)
Exceptions
nothrow
Postcondition
m_iType==cmUNKNOWN
See also
Assign
Definition at line 83 of file qmuparsertoken.h.
References qmu::QmuParserToken< TBase, TString >::Assign().
Member Function Documentation
Assign()
template<typename TBase , typename TString > void qmu::QmuParserToken< TBase, TString >::Assign (const QmuParserToken< TBase, TString > & a_Tok) inline
Copy token information from argument.
Exceptions
nothrow
Definition at line 114 of file qmuparsertoken.h.
References qmu::QmuParserToken< TBase, TString >::m_fVal, qmu::QmuParserToken< TBase, TString >::m_iCode, qmu::QmuParserToken< TBase, TString >::m_iIdx, qmu::QmuParserToken< TBase, TString >::m_iType, qmu::QmuParserToken< TBase, TString >::m_pCallback, qmu::QmuParserToken< TBase, TString >::m_pTok, qmu::QmuParserToken< TBase, TString >::m_strTok, and qmu::QmuParserToken< TBase, TString >::m_strVal.
Referenced by qmu::QmuParserToken< TBase, TString >::operator=(), and qmu::QmuParserToken< TBase, TString >::QmuParserToken().
GetArgCount()
template<typename TBase , typename TString > int qmu::QmuParserToken< TBase, TString >::GetArgCount () const inline
Return the number of function arguments.
Valid only if m_iType==CmdFUNC.
Definition at line 444 of file qmuparsertoken.h.
References qmu::ecINTERNAL_ERROR, and qmu::QmuParserToken< TBase, TString >::m_pCallback.
Referenced by qmu::QmuParserBase::ApplyFunc(), and qmu::QmuParserBase::ApplyStrFunc().
GetAssociativity()
template<typename TBase , typename TString > EOprtAssociativity qmu::QmuParserToken< TBase, TString >::GetAssociativity () const inline
Definition at line 318 of file qmuparsertoken.h.
References qmu::cmOPRT_BIN, qmu::ecINTERNAL_ERROR, and qmu::QmuParserToken< TBase, TString >::m_pCallback.
Referenced by qmu::QmuParserBase::GetOprtAssociativity().
GetAsString()
template<typename TBase , typename TString > const TString & qmu::QmuParserToken< TBase, TString >::GetAsString () const inline
Return the token identifier.
If m_iType is cmSTRING the token identifier is the value of the string argument for a string function.
Returns
m_strTok
Exceptions
nothrow
See also
m_strTok
Definition at line 466 of file qmuparsertoken.h.
References qmu::QmuParserToken< TBase, TString >::m_strTok.
Referenced by qmu::QmuParserBase::ApplyFunc(), qmu::QmuParserBase::ApplyStrFunc(), qmu::QmuParserBase::CreateRPN(), qmu::QmuParserTokenReader::IsFunTok(), qmu::QmuParserTokenReader::IsInfixOpTok(), qmu::QmuParserTokenReader::IsUndefVarTok(), and qmu::QmuParserBase::StackDump().
GetCode()
template<typename TBase , typename TString > ECmdCode qmu::QmuParserToken< TBase, TString >::GetCode () const inline
Return the token type.
Returns
m_iType
Exceptions
nothrow
Definition at line 276 of file qmuparsertoken.h.
References qmu::QmuParserToken< TBase, TString >::m_iCode, and qmu::QmuParserToken< TBase, TString >::m_pCallback.
Referenced by qmu::QmuParserBase::ApplyFunc(), qmu::QmuParserBase::ApplyIfElse(), qmu::QmuParserBase::CreateRPN(), qmu::QmuParserBase::GetOprtAssociativity(), qmu::QmuParserBase::GetOprtPrecedence(), qmu::QmuParserTokenReader::IsBuiltIn(), and qmu::QmuParserBase::StackDump().
GetFuncAddr()
template<typename TBase , typename TString > generic_fun_type qmu::QmuParserToken< TBase, TString >::GetFuncAddr () const inline
Return the address of the callback function assoziated with function and operator tokens.
Returns
The pointer stored in m_pTok.
Exceptions
QmuParserError if token type is non of:
cmFUNC
cmSTRFUNC
cmPOSTOP
cmINFIXOP
cmOPRT_BIN
See also
ECmdCode
Definition at line 361 of file qmuparsertoken.h.
References qmu::QmuParserToken< TBase, TString >::m_pCallback.
Referenced by qmu::QmuParserBase::ApplyFunc(), and qmu::QmuParserBase::ApplyStrFunc().
GetIdx()
template<typename TBase , typename TString > int qmu::QmuParserToken< TBase, TString >::GetIdx () const inline
Return Index associated with the token related data.
In cmSTRFUNC - This is the index to a string table in the main parser.
Exceptions
QmuParserError if m_iIdx<0 or m_iType!=cmSTRING
Returns
The index the result will take in the Bytecode calculatin array (m_iIdx).
Definition at line 259 of file qmuparsertoken.h.
References qmu::cmSTRING, qmu::ecINTERNAL_ERROR, qmu::QmuParserToken< TBase, TString >::m_iCode, and qmu::QmuParserToken< TBase, TString >::m_iIdx.
GetPri()
template<typename TBase , typename TString > int qmu::QmuParserToken< TBase, TString >::GetPri () const inline
Definition at line 302 of file qmuparsertoken.h.
References qmu::cmOPRT_BIN, qmu::cmOPRT_INFIX, qmu::ecINTERNAL_ERROR, and qmu::QmuParserToken< TBase, TString >::m_pCallback.
Referenced by qmu::QmuParserBase::GetOprtPrecedence().
GetType()
template<typename TBase , typename TString > ETypeCode qmu::QmuParserToken< TBase, TString >::GetType () const inline
Definition at line 289 of file qmuparsertoken.h.
References qmu::QmuParserToken< TBase, TString >::m_iType, and qmu::QmuParserToken< TBase, TString >::m_pCallback.
Referenced by qmu::QmuParserBase::ApplyBinOprt(), qmu::QmuParserBase::ApplyFunc(), and qmu::QmuParserBase::StackDump().
GetVal()
template<typename TBase , typename TString > TBase qmu::QmuParserToken< TBase, TString >::GetVal () const inline
Get value of the token.
Only applicable to variable and value tokens.
Exceptions
QmuParserError if token is no value/variable token.
Definition at line 374 of file qmuparsertoken.h.
References qmu::cmADD, qmu::cmARG_SEP, qmu::cmASSIGN, qmu::cmBC, qmu::cmBO, qmu::cmDIV, qmu::cmELSE, qmu::cmEND, qmu::cmENDIF, qmu::cmEQ, qmu::cmFUNC, qmu::cmFUNC_BULK, qmu::cmFUNC_STR, qmu::cmGE, qmu::cmGT, qmu::cmIF, qmu::cmLAND, qmu::cmLE, qmu::cmLOR, qmu::cmLT, qmu::cmMUL, qmu::cmNEQ, qmu::cmOPRT_BIN, qmu::cmOPRT_INFIX, qmu::cmOPRT_POSTFIX, qmu::cmPOW, qmu::cmPOW2, qmu::cmSTRING, qmu::cmSUB, qmu::cmUNKNOWN, qmu::cmVAL, qmu::cmVAR, qmu::cmVARMUL, qmu::cmVARPOW2, qmu::cmVARPOW3, qmu::cmVARPOW4, qmu::ecVAL_EXPECTED, qmu::QmuParserToken< TBase, TString >::m_fVal, qmu::QmuParserToken< TBase, TString >::m_iCode, and qmu::QmuParserToken< TBase, TString >::m_pTok.
Referenced by qmu::QmuParserBase::ApplyIfElse(), qmu::QmuParserBase::CreateRPN(), and qmu::QmuParserBase::StackDump().
GetVar()
template<typename TBase , typename TString > TBase * qmu::QmuParserToken< TBase, TString >::GetVar () const inline
Get address of a variable token.
Valid only if m_iType==CmdVar.
Exceptions
QmuParserError if token is no variable token.
Definition at line 428 of file qmuparsertoken.h.
References qmu::cmVAR, qmu::ecINTERNAL_ERROR, qmu::QmuParserToken< TBase, TString >::m_iCode, and qmu::QmuParserToken< TBase, TString >::m_pTok.
Referenced by qmu::QmuParserBase::CreateRPN().
operator=()
template<typename TBase , typename TString > QmuParserToken & qmu::QmuParserToken< TBase, TString >::operator= (const QmuParserToken< TBase, TString > & a_Tok) inline
Assignement operator.
Copy token state from another token and return this. Implemented by calling Assign(...).
Exceptions
nothrow
Definition at line 98 of file qmuparsertoken.h.
References qmu::QmuParserToken< TBase, TString >::Assign().
Set() [1/2]
template<typename TBase , typename TString > QmuParserToken & qmu::QmuParserToken< TBase, TString >::Set (const QmuParserCallback & a_pCallback, const TString & a_sTok) inline
Set Callback type.
Definition at line 159 of file qmuparsertoken.h.
References qmu::QmuParserCallback::GetAddr(), qmu::QmuParserCallback::GetCode(), qmu::QmuParserToken< TBase, TString >::m_iCode, qmu::QmuParserToken< TBase, TString >::m_iIdx, qmu::QmuParserToken< TBase, TString >::m_iType, qmu::QmuParserToken< TBase, TString >::m_pCallback, qmu::QmuParserToken< TBase, TString >::m_pTok, qmu::QmuParserToken< TBase, TString >::m_strTok, and qmu::tpVOID.
Set() [2/2]
template<typename TBase , typename TString > QmuParserToken & qmu::QmuParserToken< TBase, TString >::Set (ECmdCode a_iType, const TString & a_strTok = TString()) inline
Assign a token type.
Token may not be of type value, variable or function. Those have seperate set functions.
Precondition
[assert] a_iType!=cmVAR
[assert] a_iType!=cmVAL
[assert] a_iType!=cmFUNC
Postcondition
m_fVal = 0
m_pTok = 0
Definition at line 139 of file qmuparsertoken.h.
References qmu::cmFUNC, qmu::cmVAL, qmu::cmVAR, qmu::QmuParserToken< TBase, TString >::m_iCode, qmu::QmuParserToken< TBase, TString >::m_iIdx, qmu::QmuParserToken< TBase, TString >::m_iType, qmu::QmuParserToken< TBase, TString >::m_pTok, qmu::QmuParserToken< TBase, TString >::m_strTok, and qmu::tpVOID.
Referenced by qmu::QmuParserTokenReader::IsArgSep(), qmu::QmuParserTokenReader::IsBuiltIn(), qmu::QmuParserTokenReader::IsEOF(), qmu::QmuParserTokenReader::IsFunTok(), qmu::QmuParserTokenReader::IsInfixOpTok(), qmu::QmuParserTokenReader::IsOprt(), and qmu::QmuParserTokenReader::IsPostOpTok().
SetIdx()
template<typename TBase , typename TString > void qmu::QmuParserToken< TBase, TString >::SetIdx (int a_iIdx) inline
Set an index associated with the token related data.
In cmSTRFUNC - This is the index to a string table in the main parser.
Parameters
a_iIdx The index the string function result will take in the bytecode parser.
Exceptions
QmuParserError if #a_iIdx<0 or m_iType!=cmSTRING
Definition at line 240 of file qmuparsertoken.h.
References qmu::cmSTRING, qmu::ecINTERNAL_ERROR, qmu::QmuParserToken< TBase, TString >::m_iCode, and qmu::QmuParserToken< TBase, TString >::m_iIdx.
Referenced by qmu::QmuParserBase::CreateRPN().
SetString()
template<typename TBase , typename TString > QmuParserToken & qmu::QmuParserToken< TBase, TString >::SetString (const TString & a_strTok, int a_iSize) inline
Make this token a variable token.
Member variables not necessary for variable tokens will be invalidated.
Exceptions
nothrow
Definition at line 220 of file qmuparsertoken.h.
References qmu::cmSTRING, qmu::QmuParserToken< TBase, TString >::m_iCode, qmu::QmuParserToken< TBase, TString >::m_iIdx, qmu::QmuParserToken< TBase, TString >::m_iType, qmu::QmuParserToken< TBase, TString >::m_pCallback, qmu::QmuParserToken< TBase, TString >::m_pTok, qmu::QmuParserToken< TBase, TString >::m_strTok, and qmu::tpSTR.
Referenced by qmu::QmuParserTokenReader::IsString(), and qmu::QmuParserTokenReader::IsStrVarTok().
SetVal()
template<typename TBase , typename TString > QmuParserToken & qmu::QmuParserToken< TBase, TString >::SetVal (TBase a_fVal, const TString & a_strTok = TString()) inline
Make this token a value token.
Member variables not necessary for value tokens will be invalidated.
Exceptions
nothrow
Definition at line 181 of file qmuparsertoken.h.
References qmu::cmVAL, qmu::QmuParserToken< TBase, TString >::m_fVal, qmu::QmuParserToken< TBase, TString >::m_iCode, qmu::QmuParserToken< TBase, TString >::m_iIdx, qmu::QmuParserToken< TBase, TString >::m_iType, qmu::QmuParserToken< TBase, TString >::m_pCallback, qmu::QmuParserToken< TBase, TString >::m_pTok, qmu::QmuParserToken< TBase, TString >::m_strTok, and qmu::tpDBL.
Referenced by qmu::QmuParserBase::ApplyFunc(), qmu::QmuParserBase::ApplyStrFunc(), and qmu::QmuParserTokenReader::IsValTok().
SetVar()
template<typename TBase , typename TString > QmuParserToken & qmu::QmuParserToken< TBase, TString >::SetVar (TBase * a_pVar, const TString & a_strTok) inline
make this token a variable token.
Member variables not necessary for variable tokens will be invalidated.
Exceptions
nothrow
Definition at line 202 of file qmuparsertoken.h.
References qmu::cmVAR, qmu::QmuParserToken< TBase, TString >::m_iCode, qmu::QmuParserToken< TBase, TString >::m_iIdx, qmu::QmuParserToken< TBase, TString >::m_iType, qmu::QmuParserToken< TBase, TString >::m_pCallback, qmu::QmuParserToken< TBase, TString >::m_pTok, qmu::QmuParserToken< TBase, TString >::m_strTok, and qmu::tpDBL.
Referenced by qmu::QmuParserTokenReader::IsUndefVarTok(), and qmu::QmuParserTokenReader::IsVarTok().
union_cast()
template<typename TBase , typename TString > template<class FunctionPtr > static FunctionPtr qmu::QmuParserToken< TBase, TString >::union_cast (void * objectPtr) inline static
Definition at line 330 of file qmuparsertoken.h.
Member Data Documentation
m_fVal
template<typename TBase , typename TString > qreal qmu::QmuParserToken< TBase, TString >::m_fVal private
the value
Definition at line 477 of file qmuparsertoken.h.
Referenced by qmu::QmuParserToken< TBase, TString >::Assign(), qmu::QmuParserToken< TBase, TString >::GetVal(), and qmu::QmuParserToken< TBase, TString >::SetVal().
m_iCode
template<typename TBase , typename TString > ECmdCode qmu::QmuParserToken< TBase, TString >::m_iCode private
Type of the token; The token type is a constant of type ECmdCode.
Definition at line 471 of file qmuparsertoken.h.
Referenced by qmu::QmuParserToken< TBase, TString >::Assign(), qmu::QmuParserToken< TBase, TString >::GetCode(), qmu::QmuParserToken< TBase, TString >::GetIdx(), qmu::QmuParserToken< TBase, TString >::GetVal(), qmu::QmuParserToken< TBase, TString >::GetVar(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::SetIdx(), qmu::QmuParserToken< TBase, TString >::SetString(), qmu::QmuParserToken< TBase, TString >::SetVal(), and qmu::QmuParserToken< TBase, TString >::SetVar().
m_iIdx
template<typename TBase , typename TString > int qmu::QmuParserToken< TBase, TString >::m_iIdx private
An otional index to an external buffer storing the token data.
Definition at line 474 of file qmuparsertoken.h.
Referenced by qmu::QmuParserToken< TBase, TString >::Assign(), qmu::QmuParserToken< TBase, TString >::GetIdx(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::SetIdx(), qmu::QmuParserToken< TBase, TString >::SetString(), qmu::QmuParserToken< TBase, TString >::SetVal(), and qmu::QmuParserToken< TBase, TString >::SetVar().
m_iType
template<typename TBase , typename TString > ETypeCode qmu::QmuParserToken< TBase, TString >::m_iType private
Definition at line 472 of file qmuparsertoken.h.
Referenced by qmu::QmuParserToken< TBase, TString >::Assign(), qmu::QmuParserToken< TBase, TString >::GetType(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::SetString(), qmu::QmuParserToken< TBase, TString >::SetVal(), and qmu::QmuParserToken< TBase, TString >::SetVar().
m_pCallback
template<typename TBase , typename TString > std::unique_ptr<QmuParserCallback> qmu::QmuParserToken< TBase, TString >::m_pCallback private
Definition at line 478 of file qmuparsertoken.h.
Referenced by qmu::QmuParserToken< TBase, TString >::Assign(), qmu::QmuParserToken< TBase, TString >::GetArgCount(), qmu::QmuParserToken< TBase, TString >::GetAssociativity(), qmu::QmuParserToken< TBase, TString >::GetCode(), qmu::QmuParserToken< TBase, TString >::GetFuncAddr(), qmu::QmuParserToken< TBase, TString >::GetPri(), qmu::QmuParserToken< TBase, TString >::GetType(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::SetString(), qmu::QmuParserToken< TBase, TString >::SetVal(), and qmu::QmuParserToken< TBase, TString >::SetVar().
m_pTok
template<typename TBase , typename TString > void* qmu::QmuParserToken< TBase, TString >::m_pTok private
Stores Token pointer; not applicable for all tokens.
Definition at line 473 of file qmuparsertoken.h.
Referenced by qmu::QmuParserToken< TBase, TString >::Assign(), qmu::QmuParserToken< TBase, TString >::GetVal(), qmu::QmuParserToken< TBase, TString >::GetVar(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::SetString(), qmu::QmuParserToken< TBase, TString >::SetVal(), and qmu::QmuParserToken< TBase, TString >::SetVar().
m_strTok
template<typename TBase , typename TString > TString qmu::QmuParserToken< TBase, TString >::m_strTok private
Token string.
Definition at line 475 of file qmuparsertoken.h.
Referenced by qmu::QmuParserToken< TBase, TString >::Assign(), qmu::QmuParserToken< TBase, TString >::GetAsString(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::Set(), qmu::QmuParserToken< TBase, TString >::SetString(), qmu::QmuParserToken< TBase, TString >::SetVal(), and qmu::QmuParserToken< TBase, TString >::SetVar().
m_strVal
template<typename TBase , typename TString > TString qmu::QmuParserToken< TBase, TString >::m_strVal private
Value for string variables.
Definition at line 476 of file qmuparsertoken.h.
Referenced by qmu::QmuParserToken< TBase, TString >::Assign().
The documentation for this class was generated from the following file:
src/libs/qmuparser/qmuparsertoken.h