# project: SeamlyLayout
# author: slspencer, copyright 2026
# MIT License: https://opensource.org/licenses/MIT
#
# @file generate_license_notices.py
# @brief Regenerates the committed third-party license notices shipped in every installer.
#
# Writes, next to this script:
#   rust_crate_notices.txt  every Rust crate linked into SeamlyLayout, with its license text
#                           (cargo-about; config about.toml, template rust_crate_notices.hbs)
#   qt_notices.txt          the Qt runtime under LGPL-3.0, its modules and bundled third-party
#                           components, with every license text they need (from the Qt kit SBOMs)
#
# Run it after any Cargo.lock change or Qt version change:
#   python generate_license_notices.py --qt-root C:/Qt/6.11.1/msvc2022_64
# Requires: cargo-about on PATH (cargo install cargo-about --locked --features cli), network access for the
# SPDX license texts. cargo test (cxxqt_bridge, license_notices_tests) fails while either file is stale.

import argparse
import json
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
WORKSPACE = HERE.parents[1]  # src/app/seamlylayout
CARGO_LOCK = WORKSPACE / "Cargo.lock"
BRIDGE_MANIFEST = WORKSPACE / "crates" / "cxxqt_bridge" / "Cargo.toml"

# Qt repositories whose libraries, plugins or QML modules the installers deploy.
SHIPPED_QT_REPOS = [
    "qtbase", "qtdeclarative", "qtimageformats", "qtmultimedia", "qtpdf", "qtpositioning",
    "qtserialport", "qtsvg", "qttranslations", "qtwebchannel", "qtwebengine",
    "qtwebengine-chromium-webengine", "qtwebengine-chromium-pdf",
]

# Qt's own modules are offered under several licenses; SeamlyLayout, Seamly2D and SeamlyMe use LGPL-3.0-only.
QT_OWN_LICENSE = "LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"
QT_COMMERCIAL_OR = "LicenseRef-Qt-Commercial OR "

SPDX_TEXT_URL = "https://raw.githubusercontent.com/spdx/license-list-data/main/text/{}.txt"

RULE = "=" * 78
THIN = "-" * 78


def fnv1a64(data: bytes) -> str:
    """Stable 64-bit FNV-1a hash as 16 hex digits; the Rust staleness test computes the same value."""
    h = 0xCBF29CE484222325
    for b in data:
        h ^= b
        h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return f"{h:016x}"


def cargo_lock_fingerprint() -> str:
    """Fingerprint of Cargo.lock with CRLF normalised to LF, so a checkout's line endings do not matter."""
    return "fnv1a64:" + fnv1a64(CARGO_LOCK.read_bytes().replace(b"\r\n", b"\n"))


def write_lf(path: Path, text: str) -> None:
    """Write UTF-8 text with LF line endings."""
    path.write_bytes(text.replace("\r\n", "\n").encode("utf-8"))


def generate_rust() -> None:
    """Run cargo-about and prepend the header the staleness test reads."""
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "body.txt"
        subprocess.run(
            ["cargo", "about", "generate",
             "-c", str(HERE / "about.toml"),
             "--manifest-path", str(BRIDGE_MANIFEST),
             "-o", str(out),
             str(HERE / "rust_crate_notices.hbs")],
            check=True, cwd=WORKSPACE)
        body = out.read_text(encoding="utf-8")
    header = (
        "Third-party Rust crates in SeamlyLayout\n"
        "\n"
        "SeamlyLayout links the Rust crates below. Each license text follows the list\n"
        "of crates that use it. SeamlyLayout's own crates (MIT) are listed too.\n"
        "Generated by generate_license_notices.py with cargo-about.\n"
        "\n"
        f"Cargo.lock fingerprint: {cargo_lock_fingerprint()}\n"
        "\n")
    write_lf(HERE / "rust_crate_notices.txt", header + body.strip("\n") + "\n")


def license_ids(expression: str) -> list:
    """SPDX ids and exception ids in a license expression, in order, without duplicates."""
    ids = []
    for token in re.split(r"[()\s]+", expression):
        if token and token not in ("AND", "OR", "WITH") and token not in ids:
            ids.append(token)
    return ids


def fetch_spdx_text(spdx_id: str, cache: dict) -> str:
    """Standard license or exception text from the SPDX license list (CC0)."""
    if spdx_id not in cache:
        with urllib.request.urlopen(SPDX_TEXT_URL.format(spdx_id)) as response:
            cache[spdx_id] = response.read().decode("utf-8")
    return cache[spdx_id]


def qt_version(qt_root: Path) -> str:
    """Qt version of the kit, read from its SBOM file names (e.g. qtbase-6.11.1.spdx.json)."""
    match = next((qt_root / "sbom").glob("qtbase-*.spdx.json"), None)
    if match is None:
        sys.exit(f"no Qt SBOM in {qt_root / 'sbom'}: pass --qt-root <Qt kit directory>")
    return match.name[len("qtbase-"):-len(".spdx.json")]


def generate_qt(qt_root: Path) -> None:
    """Build qt_notices.txt from the SBOMs of the Qt repositories the installers ship."""
    version = qt_version(qt_root)
    minor = ".".join(version.split(".")[:2])
    sections = []
    used_ids = []
    extracted = {}
    for repo in SHIPPED_QT_REPOS:
        doc = json.loads((qt_root / "sbom" / f"{repo}-{version}.spdx.json").read_text(encoding="utf-8"))
        for info in doc.get("hasExtractedLicensingInfos", []):
            extracted[info["licenseId"]] = info.get("extractedText", "")
        rows = []
        for pkg in doc["packages"]:
            # Build tools (moc, syncqt, bootstrap libraries) and test libraries are not shipped.
            name = pkg["name"]
            if pkg.get("primaryPackagePurpose") == "APPLICATION" or name.startswith("Bootstrap") or "Test" in name:
                continue
            expression = pkg.get("licenseConcluded", "NOASSERTION")
            if expression == "NOASSERTION":
                continue
            if expression == QT_OWN_LICENSE:
                expression = "LGPL-3.0-only"  # the option these applications use
            elif expression.startswith(QT_COMMERCIAL_OR):
                expression = expression[len(QT_COMMERCIAL_OR):]  # the open-source option
            for spdx_id in license_ids(expression):
                if spdx_id not in used_ids:
                    used_ids.append(spdx_id)
            copyright_text = pkg.get("copyrightText", "NOASSERTION")
            line = f"  - {pkg['name']} {pkg.get('versionInfo') or ''}".rstrip() + f"  [{expression}]"
            if copyright_text not in ("NOASSERTION", ""):
                line += "\n      " + copyright_text.replace("\n", "\n      ")
            rows.append(line)
        sections.append(f"{repo} {version}\n" + "\n".join(sorted(set(rows))))

    cache = {}
    texts = []
    for spdx_id in used_ids:
        if spdx_id.startswith("LicenseRef-"):
            text = extracted.get(spdx_id, "")
        else:
            text = fetch_spdx_text(spdx_id, cache)
        texts.append(f"{RULE}\n{spdx_id}\n{THIN}\n{text.strip()}\n")

    header = (
        "Qt runtime in Seamly2D, SeamlyMe and SeamlyLayout\n"
        "\n"
        f"Qt version: {version}\n"
        "\n"
        "These applications use the Qt libraries under the GNU Lesser General Public\n"
        "License version 3 (LGPL-3.0-only). Qt is Copyright (C) The Qt Company Ltd. and\n"
        "other contributors. The Qt libraries are dynamically linked and installed as\n"
        "separate files; you may replace them with a compatible build of your own.\n"
        "\n"
        "Qt source code for this version:\n"
        f"  https://download.qt.io/official_releases/qt/{minor}/{version}/single/\n"
        "\n"
        "Qt bundles third-party components. Each shipped Qt repository lists them below\n"
        "with their license and copyright; the full license texts follow at the end.\n"
        "Generated by generate_license_notices.py from the Qt kit's SPDX SBOM files.\n"
        "\n")
    body = f"{RULE}\n" + f"\n\n".join(sections) + "\n\n" + RULE + "\nLICENSE TEXTS\n\n" + "\n".join(texts)
    write_lf(HERE / "qt_notices.txt", header + body)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--qt-root", type=Path, required=True, help="Qt kit directory, e.g. C:/Qt/6.11.1/msvc2022_64")
    parser.add_argument("--skip-rust", action="store_true", help="regenerate qt_notices.txt only")
    parser.add_argument("--skip-qt", action="store_true", help="regenerate rust_crate_notices.txt only")
    args = parser.parse_args()
    if not args.skip_rust:
        generate_rust()
    if not args.skip_qt:
        generate_qt(args.qt_root)


if __name__ == "__main__":
    main()
